# Generated by Django 4.1.1 on 2022-12-03 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="notes",
            new_name="body",
        ),
    ]
