databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
envs:
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
name: seal-app
region: nyc
services:
- environment_slug: python
  envs:
  - key: DATABASE_ENGINE
    scope: RUN_TIME
    value: django.db.backends.sqlite3
  - key: DATABASE_NAME
    scope: RUN_AND_BUILD_TIME
    value: config/superhero.db
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE_URL}
  - key: POSTGRES_DB
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE}
  - key: POSTGRES_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${db.HOSTNAME}
  - key: POSTGRES_USER
    scope: RUN_AND_BUILD_TIME
    value: ${db.USERNAME}
  - key: POSTGRES_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: ${db.PASSWORD}
  - key: POSTGRES_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${db.PORT}
  - key: DJANGO_SUPERUSER_EMAIL
    scope: RUN_AND_BUILD_TIME
    value: josh.m.flatt@gmail.com
  - key: DJANGO_SUPERUSER_USERNAME
    scope: RUN_AND_BUILD_TIME
    value: flatt44
  - key: DJANGO_SUPERUSER_PASSWORD
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:FbM/rZflv9hGyyte/rf+GfhblPaa/F1k:0m+9Erh3PzmKkQcF2b8BbPal3q8xQwf1OezWAYaPrcU=]
  github:
    branch: main
    deploy_on_push: true
    repo: josh-flatt/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: superheroapp
  routes:
  - path: /
  run_command: |-
    python manage.py migrate --no-input
    python manage.py createsuperuser --no-input
    gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: Superhero
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: josh-flatt/PythonWebApps
  name: superheroapp-static
  routes:
  - path: /static
  source_dir: Superhero/static
