# Generated by Django 4.1.1 on 2022-12-03 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="superhero",
            name="image",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="hero.photo"
            ),
        ),
    ]
