# Generated by Django 4.1.1 on 2022-11-12 05:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hero', '0002_article_delete_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Investigator',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='investigator',
        ),
        migrations.RenameField(
            model_name='superhero',
            old_name='author',
            new_name='investigator',
        ),
    ]
